#!/bin/sh

trap : INT TERM QUIT

command=$*
eval "$@"
status=$?

if [ $status -eq 0 ]; then
    color="good"
    text=":white_check_mark:"
else
    color="danger"
    text=":x:"
fi

echo "{
    \"username\": \"pingu\",
    \"icon_emoji\": \":penguin:\",
    \"attachments\": [
        {
            \"fallback\": \"${text} ${command}\",
            \"text\": \"${text} \`${command}\`\",
            \"color\": \"${color}\",
            \"footer\": \"$(hostname)\"
        }
    ]
}" | curl -sSLd @- "${SLACK_WEBHOOK_URL}" > /dev/null

exit ${status}
