#!/bin/sh

trap : INT TERM QUIT

escape() {
    sed 's/"/\\"/g'
}

eval "$@"
status=$?

if [ ${status} -eq 0 ]; then
    color="good"
    emoji=":white_check_mark:"
else
    color="danger"
    emoji=":x:"
fi
text=$(echo "${emoji} \`$*\`" | escape)
fallback=$(echo "${emoji} $*" | escape)
footer=$(id -un)@$(uname -n)

echo '{
    "username": "pingu",
    "icon_emoji": ":penguin:",
    "attachments": [
         {
            "text": "'"${text}"'",
            "fallback": "'"${fallback}"'",
            "color": "'"${color}"'",
            "footer": "'"${footer}"'"
        }
    ]
}' | curl -sSLd @- "${SLACK_WEBHOOK_URL}" > /dev/null

exit ${status}
