#!/usr/bin/env bash

trap : INT TERM QUIT

source ~/.pingurc

start=$(date +%s)
command=$*
"$@"
status=$?
if [[ ${status} -eq 0 ]]; then
    color="good"
    text="All good"
else
    color="danger"
    text="Exited with code ${status}"
fi

echo " 
{
    'username': 'pingu', 
    'icon_emoji': ':penguin:',
    'attachments': [
        {
            'fallback': '${text}',
            'text': '${text}\n${command}',
            'color': '${color}',
            'footer': '$(hostname)',
            'ts': '${start}'
        }
    ]
}
" | tr "'" '"' | curl -sSLd @- "${webhook}" > /dev/null

exit ${status}
